# -*- coding: utf-8 -*-
"""karnataka_Rank_Score_UGNEET_2025ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10U9H6UwhnjoI6ax6eSQoE6UlQdaKZunM
"""

!pip install pdfplumber

import pdfplumber
import pandas as pd
import re

def extract_neet_data(pdf_path):
    """
    Extract NEET data from PDF with 2-column side-by-side layout.
    Left column: entries 1-35, Right column: entries 36-70 (on same page)
    """
    all_data = []

    with pdfplumber.open(pdf_path) as pdf:
        for page_num, page in enumerate(pdf.pages, 1):
            print(f"Processing page {page_num}...")

            # Get page dimensions
            page_width = page.width
            page_height = page.height

            # Define bounding boxes for left and right columns
            # Left column: 0 to 50% of page width
            left_bbox = (0, 0, page_width * 0.5, page_height)
            # Right column: 50% to 100% of page width
            right_bbox = (page_width * 0.5, 0, page_width, page_height)

            # Extract left column
            left_crop = page.crop(left_bbox)
            left_text = left_crop.extract_text()

            # Extract right column
            right_crop = page.crop(right_bbox)
            right_text = right_crop.extract_text()

            # Pattern to match data rows
            # Format: SL.NO NEET_Roll_No NEET_RANK NEET_SCORE
            pattern = r'(\d+)\s+(\d{10})\s+(\d+)\s+(\d+)'

            # Process left column first
            if left_text:
                for line in left_text.split('\n'):
                    match = re.search(pattern, line)
                    if match:
                        all_data.append({
                            'SL.NO': int(match.group(1)),
                            'NEET Roll No': match.group(2),
                            'NEET RANK': int(match.group(3)),
                            'NEET SCORE': int(match.group(4))
                        })

            # Then process right column
            if right_text:
                for line in right_text.split('\n'):
                    match = re.search(pattern, line)
                    if match:
                        all_data.append({
                            'SL.NO': int(match.group(1)),
                            'NEET Roll No': match.group(2),
                            'NEET RANK': int(match.group(3)),
                            'NEET SCORE': int(match.group(4))
                        })

    # Create DataFrame and sort by SL.NO
    df = pd.DataFrame(all_data)
    df = df.sort_values('SL.NO').reset_index(drop=True)

    # Remove duplicates if any (keep first occurrence)
    df = df.drop_duplicates(subset=['SL.NO'], keep='first')

    return df


def main():
    # Specify your PDF file path
    pdf_path = '/content/karnataka_Rank_Score_UGNEET_2025_Clamined_kqarnataka_Seat.pdf'

    print("Starting PDF extraction...")
    print("Extracting data from side-by-side columns...\n")

    # Extract data
    df = extract_neet_data(pdf_path)

    # Display results
    print(f"\nTotal records extracted: {len(df)}")
    print("\n" + "="*60)
    print("First 10 records:")
    print("="*60)
    print(df.head(10).to_string(index=False))

    print("\n" + "="*60)
    print("Records 35-42 (to verify column separation):")
    print("="*60)
    print(df[df['SL.NO'].between(35, 42)].to_string(index=False))

    print("\n" + "="*60)
    print("Last 10 records:")
    print("="*60)
    print(df.tail(10).to_string(index=False))

    # Save to CSV
    output_csv = 'neet_data_extracted.csv'
    df.to_csv(output_csv, index=False)
    print(f"\n✓ Data saved to: {output_csv}")

    # Save to Excel
    output_excel = 'neet_data_extracted.xlsx'
    df.to_excel(output_excel, index=False)
    print(f"✓ Data saved to: {output_excel}")

    # Display statistics
    print("\n" + "="*60)
    print("STATISTICS")
    print("="*60)
    print(f"Total Candidates: {len(df)}")
    print(f"SL.NO Range: {df['SL.NO'].min()} - {df['SL.NO'].max()}")
    print(f"NEET Score Range: {df['NEET SCORE'].min()} - {df['NEET SCORE'].max()}")
    print(f"NEET Rank Range: {df['NEET RANK'].min()} - {df['NEET RANK'].max()}")

    # Check for missing serial numbers
    expected_sl_nos = set(range(df['SL.NO'].min(), df['SL.NO'].max() + 1))
    actual_sl_nos = set(df['SL.NO'])
    missing_sl_nos = expected_sl_nos - actual_sl_nos

    if missing_sl_nos:
        print(f"\n⚠ Warning: Missing SL.NO entries: {sorted(missing_sl_nos)}")
    else:
        print(f"\n✓ All serial numbers from {df['SL.NO'].min()} to {df['SL.NO'].max()} are present")

    print("="*60)


if __name__ == "__main__":
    main()





