# -*- coding: utf-8 -*-
"""KH+SeatMatric.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QE1l260SQnRLWMvqdZe12edaGIMmC3mi
"""

!pip install PyPDF2
!pip install pdfplumber tabula-py

import pandas as pd
import tabula
from pathlib import Path
import warnings
warnings.filterwarnings('ignore')

def extract_tables_from_pdf(pdf_path):
    """
    Extract tables from PDF using tabula with optimized settings
    """
    try:
        # Extract tables from first 3 pages (pages 1, 2, 3)
        print("Extracting tables from pages 1-3...")
        tables_p1_3 = tabula.read_pdf(
            pdf_path,
            pages='1-3',
            multiple_tables=True,
            lattice=True,  # Use lattice mode for structured tables
            pandas_options={'header': None}
        )

        # Extract from page 4 with different settings
        print("Extracting table from page 4...")
        tables_p4 = tabula.read_pdf(
            pdf_path,
            pages='4',
            multiple_tables=True,
            lattice=True,
            pandas_options={'header': None}
        )

        return tables_p1_3, tables_p4

    except Exception as e:
        print(f"Tabula extraction failed: {e}")
        return None, None

def clean_dataframe(df):
    """
    Clean and standardize the dataframe
    """
    # Remove completely empty rows
    df = df.dropna(how='all')

    # Remove rows where all values are NaN or empty strings
    df = df[~df.apply(lambda x: x.astype(str).str.strip().eq('').all(), axis=1)]

    # Reset index
    df = df.reset_index(drop=True)

    return df

def merge_tables(tables_list):
    """
    Merge multiple tables intelligently
    """
    if not tables_list:
        return None

    cleaned_tables = []
    for i, table in enumerate(tables_list):
        print(f"  Processing table {i+1}: Shape {table.shape}")
        cleaned = clean_dataframe(table)
        if not cleaned.empty:
            cleaned_tables.append(cleaned)

    if not cleaned_tables:
        return None

    # Try to concatenate tables with same number of columns
    result_tables = []
    current_group = [cleaned_tables[0]]
    current_cols = cleaned_tables[0].shape[1]

    for table in cleaned_tables[1:]:
        if table.shape[1] == current_cols:
            current_group.append(table)
        else:
            # Save current group and start new one
            if current_group:
                result_tables.append(pd.concat(current_group, ignore_index=True))
            current_group = [table]
            current_cols = table.shape[1]

    # Add last group
    if current_group:
        result_tables.append(pd.concat(current_group, ignore_index=True))

    return result_tables

def extract_with_alternate_method(pdf_path, pages):
    """
    Alternate extraction method with stream mode
    """
    try:
        print(f"Trying alternate extraction for pages {pages}...")
        tables = tabula.read_pdf(
            pdf_path,
            pages=pages,
            multiple_tables=True,
            stream=True,  # Use stream mode instead of lattice
            pandas_options={'header': None}
        )
        return tables
    except Exception as e:
        print(f"Alternate extraction failed: {e}")
        return None

def main(pdf_path):
    """
    Main extraction function - outputs only Excel file
    """
    pdf_path = Path(pdf_path)

    if not pdf_path.exists():
        print(f"❌ Error: File not found at {pdf_path}")
        return

    print(f"\n{'='*60}")
    print(f"📄 Processing PDF: {pdf_path.name}")
    print(f"{'='*60}\n")

    # Extract tables from pages 1-3 and page 4 separately
    tables_p1_3, tables_p4 = extract_tables_from_pdf(pdf_path)

    if tables_p1_3 is None and tables_p4 is None:
        print("❌ Failed to extract any tables. Trying alternate method...")

        # Try alternate extraction
        tables_p1_3 = extract_with_alternate_method(pdf_path, '1-3')
        tables_p4 = extract_with_alternate_method(pdf_path, '4')

    # Prepare Excel writer
    output_excel = pdf_path.stem + '_extracted.xlsx'

    with pd.ExcelWriter(output_excel, engine='openpyxl') as writer:
        sheet_number = 1

        # Process pages 1-3
        if tables_p1_3:
            print(f"\n📊 Found {len(tables_p1_3)} tables in pages 1-3")
            merged_p1_3 = merge_tables(tables_p1_3)

            if merged_p1_3:
                for i, table in enumerate(merged_p1_3):
                    sheet_name = f'Pages_1-3_Table_{i+1}'
                    table.to_excel(writer, sheet_name=sheet_name, index=False, header=False)
                    print(f"  ✓ Saved {sheet_name}: {table.shape[0]} rows × {table.shape[1]} columns")
                    sheet_number += 1

                # Also save combined pages 1-3
                combined_p1_3 = pd.concat(merged_p1_3, ignore_index=True)
                combined_p1_3.to_excel(writer, sheet_name='Pages_1-3_Combined', index=False, header=False)
                print(f"  ✓ Saved Pages_1-3_Combined: {combined_p1_3.shape[0]} rows × {combined_p1_3.shape[1]} columns")

        # Process page 4 separately
        if tables_p4:
            print(f"\n📊 Found {len(tables_p4)} tables in page 4")
            merged_p4 = merge_tables(tables_p4)

            if merged_p4:
                for i, table in enumerate(merged_p4):
                    sheet_name = f'Page_4_Table_{i+1}'
                    table.to_excel(writer, sheet_name=sheet_name, index=False, header=False)
                    print(f"  ✓ Saved {sheet_name}: {table.shape[0]} rows × {table.shape[1]} columns")
                    sheet_number += 1

                # Also save combined page 4
                combined_p4 = pd.concat(merged_p4, ignore_index=True)
                combined_p4.to_excel(writer, sheet_name='Page_4_Combined', index=False, header=False)
                print(f"  ✓ Saved Page_4_Combined: {combined_p4.shape[0]} rows × {combined_p4.shape[1]} columns")

        # Try to create a master sheet with all data
        try:
            all_tables = []
            if tables_p1_3:
                all_tables.extend(tables_p1_3)
            if tables_p4:
                all_tables.extend(tables_p4)

            if all_tables:
                # Find the most common column count
                col_counts = [t.shape[1] for t in all_tables]
                most_common_cols = max(set(col_counts), key=col_counts.count)

                # Only combine tables with the same column count
                compatible_tables = [t for t in all_tables if t.shape[1] == most_common_cols]

                if compatible_tables:
                    master_df = pd.concat(compatible_tables, ignore_index=True)
                    master_df = clean_dataframe(master_df)
                    master_df.to_excel(writer, sheet_name='All_Data_Combined', index=False, header=False)
                    print(f"\n  ✓ Saved All_Data_Combined: {master_df.shape[0]} rows × {master_df.shape[1]} columns")
        except Exception as e:
            print(f"  ⚠ Could not create combined sheet: {e}")

    print(f"\n{'='*60}")
    print(f"✅ Extraction complete!")
    print(f"📁 Output saved to: {output_excel}")
    print(f"{'='*60}\n")

if __name__ == "__main__":
    print("\n" + "="*60)
    print("🏥 Dental Seat Matrix PDF Extractor")
    print("="*60)

    # Get PDF path from user
    pdf_path = "/content/Dental_first_round_seat_matrix_2025.pdf"

    main(pdf_path)

    input("\nPress Enter to exit...")







import pandas as pd
import tabula
from pathlib import Path
import warnings
warnings.filterwarnings('ignore')

def detect_pdf_type(pdf_path):
    """
    Detect if PDF is MBBS or Dental based on filename or content
    """
    filename = Path(pdf_path).name.lower()

    if 'dental' in filename or 'bds' in filename:
        return 'DENTAL'
    elif 'mbbs' in filename or 'medical' in filename:
        return 'MBBS'
    else:
        # Try to detect from first page content
        try:
            first_page = tabula.read_pdf(pdf_path, pages='1', multiple_tables=True)
            if first_page:
                text = str(first_page[0]).lower()
                if 'dental' in text or 'bds' in text:
                    return 'DENTAL'
                elif 'mbbs' in text or 'medical' in text:
                    return 'MBBS'
        except:
            pass

    return 'UNKNOWN'

def get_total_pages(pdf_path):
    """
    Get total number of pages in PDF
    """
    try:
        import PyPDF2
        with open(pdf_path, 'rb') as file:
            pdf_reader = PyPDF2.PdfReader(file)
            return len(pdf_reader.pages)
    except:
        return None

def extract_tables_smart(pdf_path, pdf_type):
    """
    Extract tables with smart page handling
    """
    total_pages = get_total_pages(pdf_path)

    if total_pages:
        print(f"📄 Total pages in PDF: {total_pages}")

    all_tables = []

    # Extract page by page for better control
    pages_to_extract = total_pages if total_pages else 10  # fallback to 10 if can't detect

    for page_num in range(1, min(pages_to_extract + 1, 20)):  # Max 20 pages
        try:
            print(f"  Extracting page {page_num}...", end=" ")

            # Try lattice mode first (better for structured tables)
            tables = tabula.read_pdf(
                pdf_path,
                pages=str(page_num),
                multiple_tables=True,
                lattice=True,
                pandas_options={'header': None}
            )

            if tables and len(tables) > 0:
                for table in tables:
                    if not table.empty and table.shape[0] > 2:  # Only keep non-empty tables
                        all_tables.append({
                            'page': page_num,
                            'data': table
                        })
                print(f"✓ Found {len(tables)} table(s)")
            else:
                # Try stream mode if lattice fails
                tables = tabula.read_pdf(
                    pdf_path,
                    pages=str(page_num),
                    multiple_tables=True,
                    stream=True,
                    pandas_options={'header': None}
                )

                if tables and len(tables) > 0:
                    for table in tables:
                        if not table.empty and table.shape[0] > 2:
                            all_tables.append({
                                'page': page_num,
                                'data': table
                            })
                    print(f"✓ Found {len(tables)} table(s) (stream mode)")
                else:
                    print("⚠ No tables found")

        except Exception as e:
            print(f"✗ Error: {str(e)[:50]}")
            continue

    return all_tables

def clean_dataframe(df):
    """
    Clean and standardize the dataframe
    """
    # Remove completely empty rows
    df = df.dropna(how='all')

    # Remove rows where all values are empty strings
    df = df[~df.apply(lambda x: x.astype(str).str.strip().eq('').all(), axis=1)]

    # Reset index
    df = df.reset_index(drop=True)

    return df

def save_to_excel(all_tables, output_path, pdf_type):
    """
    Save all extracted tables to a single Excel file
    """
    with pd.ExcelWriter(output_path, engine='openpyxl') as writer:

        # Group tables by page
        pages = {}
        for item in all_tables:
            page_num = item['page']
            if page_num not in pages:
                pages[page_num] = []
            pages[page_num].append(item['data'])

        # Save each page's tables
        for page_num in sorted(pages.keys()):
            tables = pages[page_num]

            for idx, table in enumerate(tables):
                cleaned_table = clean_dataframe(table)

                if not cleaned_table.empty:
                    sheet_name = f'Page_{page_num}_Table_{idx+1}'
                    # Excel sheet names max 31 characters
                    sheet_name = sheet_name[:31]

                    cleaned_table.to_excel(writer, sheet_name=sheet_name, index=False, header=False)
                    print(f"  ✓ Saved {sheet_name}: {cleaned_table.shape[0]} rows × {cleaned_table.shape[1]} cols")

        # Create combined sheets by page
        for page_num in sorted(pages.keys()):
            try:
                tables = pages[page_num]

                # Find most common column count
                col_counts = [t.shape[1] for t in tables]
                if col_counts:
                    most_common_cols = max(set(col_counts), key=col_counts.count)

                    # Combine tables with same column count
                    compatible = [t for t in tables if t.shape[1] == most_common_cols]

                    if compatible:
                        combined = pd.concat(compatible, ignore_index=True)
                        combined = clean_dataframe(combined)

                        sheet_name = f'Page_{page_num}_Combined'[:31]
                        combined.to_excel(writer, sheet_name=sheet_name, index=False, header=False)
                        print(f"  ✓ Saved {sheet_name}: {combined.shape[0]} rows × {combined.shape[1]} cols")
            except Exception as e:
                print(f"  ⚠ Could not create combined sheet for page {page_num}")

        # Try to create master combined sheet
        try:
            all_data_tables = [item['data'] for item in all_tables]
            col_counts = [t.shape[1] for t in all_data_tables]

            if col_counts:
                most_common_cols = max(set(col_counts), key=col_counts.count)
                compatible = [t for t in all_data_tables if t.shape[1] == most_common_cols]

                if compatible:
                    master = pd.concat(compatible, ignore_index=True)
                    master = clean_dataframe(master)

                    master.to_excel(writer, sheet_name='All_Data_Combined', index=False, header=False)
                    print(f"\n  ✓ Saved All_Data_Combined: {master.shape[0]} rows × {master.shape[1]} cols")
        except Exception as e:
            print(f"  ⚠ Could not create master combined sheet")

def main(pdf_path):
    """
    Main extraction function
    """
    pdf_path = Path(pdf_path)

    if not pdf_path.exists():
        print(f"❌ Error: File not found at {pdf_path}")
        return

    print(f"\n{'='*70}")
    print(f"🏥 PDF Table Extractor")
    print(f"{'='*70}\n")
    print(f"📁 File: {pdf_path.name}")

    # Detect PDF type
    pdf_type = detect_pdf_type(pdf_path)
    print(f"📋 Type: {pdf_type}")

    print(f"\n{'='*70}")
    print("🔍 Starting extraction...")
    print(f"{'='*70}\n")

    # Extract all tables
    all_tables = extract_tables_smart(pdf_path, pdf_type)

    if not all_tables:
        print("\n❌ No tables found in PDF!")
        return

    print(f"\n{'='*70}")
    print(f"💾 Saving to Excel...")
    print(f"{'='*70}\n")

    # Save to Excel
    output_excel = pdf_path.stem + '_extracted.xlsx'
    save_to_excel(all_tables, output_excel, pdf_type)

    print(f"\n{'='*70}")
    print(f"✅ Extraction Complete!")
    print(f"{'='*70}")
    print(f"📊 Total tables extracted: {len(all_tables)}")
    print(f"📁 Output file: {output_excel}")
    print(f"{'='*70}\n")

if __name__ == "__main__":
    print("\n" + "="*70)
    print("🏥 Medical/Dental Seat Matrix PDF Extractor")
    print("="*70)
    print("\nSupports:")
    print("  • MBBS First Round Seat Matrix")
    print("  • Dental (BDS) First Round Seat Matrix")
    print("="*70)

    # Get PDF path from user
    pdf_path = "/content/Dental_first_round_seat_matrix_2025.pdf"

    # Or uncomment and set your path directly:
    # pdf_path = "Dental_first_round_seat_matrix_2025.pdf"
    # pdf_path = "mbbs_First_round_seat_matrix_2025.pdf"

    main(pdf_path)

    input("\n✓ Press Enter to exit...")



