# -*- coding: utf-8 -*-
"""PSL+Extraction+karnataka.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rGlC8gBf9YTv0PBdQtSg6eqBoPgldBaO
"""

!pip install pdfplumber openpyxl





import re
import pdfplumber
import pandas as pd
from google.colab import files

def extract_mbbs_table(pdf_path):
    """
    Extract MBBS data using table extraction - PDFs have proper table structure
    """
    all_data = []

    with pdfplumber.open(pdf_path) as pdf:
        print(f"📄 Processing {len(pdf.pages)} pages...")

        for page_num, page in enumerate(pdf.pages, 1):
            print(f"   Page {page_num}...", end=" ")

            # Extract tables from the page
            tables = page.extract_tables()

            if tables:
                for table in tables:
                    for row in table:
                        # Skip empty rows or header rows
                        if not row or not row[0]:
                            continue

                        # Skip headers
                        if 'SL.NO' in str(row[0]) or 'All India' in str(row[0]):
                            continue

                        # Check if first column is a number (SL.NO)
                        try:
                            sl_no = int(str(row[0]).strip())
                        except:
                            continue

                        # Extract all columns
                        try:
                            rank = int(str(row[1]).strip()) if len(row) > 1 and row[1] else 0
                            code = str(row[2]).strip() if len(row) > 2 and row[2] else ""

                            # Fix college name - add space after commas where missing
                            college = str(row[3]).strip() if len(row) > 3 and row[3] else ""
                            college = re.sub(r',([A-Z])', r', \1', college)  # Add space after comma before capital letter
                            college = re.sub(r'\s+', ' ', college)  # Clean multiple spaces

                            course = str(row[4]).strip() if len(row) > 4 and row[4] else ""
                            category = str(row[5]).strip() if len(row) > 5 and row[5] else ""
                            fees_str = str(row[6]).strip() if len(row) > 6 and row[6] else "0"

                            # Clean fees - extract numbers only
                            fees = int(re.sub(r'[^\d]', '', fees_str)) if fees_str else 0

                            all_data.append({
                                'SL.NO': sl_no,
                                'All India Rank': rank,
                                'Course Code': code,
                                'Name of the College Allotted': college,
                                'Course Name Allotted': course,
                                'Allotted Category': category,
                                'Course_fees': fees
                            })

                        except Exception as e:
                            print(f"\n   ⚠️ Error parsing row {row}: {e}")
                            continue

                print(f"✓ ({len([r for t in tables for r in t])} rows)")
            else:
                print("✗ No tables found")

    return all_data


# MAIN EXECUTION
print("📂 Upload your MBBS allotment PDF:")
uploaded = files.upload()
pdf_path = list(uploaded.keys())[0]

print(f"\n🔄 Processing: {pdf_path}\n")

# Extract data using table extraction
data = extract_mbbs_table(pdf_path)

if not data:
    print("\n❌ NO DATA EXTRACTED!")
    print("The PDF might not have a proper table structure.")
else:
    df = pd.DataFrame(data).sort_values('SL.NO').reset_index(drop=True)
    print(f"\n✅ Extracted {len(df)} records\n")

    # Display first 20 records
    print("📋 First 20 Records:")
    print("="*140)
    print(f"{'SL':>3} | {'Rank':>6} | {'Code':>7} | {'College':<50} | {'Course':<12} | {'Cat':<4} | {'Fees':>10}")
    print("="*140)

    for idx in range(min(20, len(df))):
        row = df.iloc[idx]
        college_short = row['Name of the College Allotted'][:47] + "..." if len(row['Name of the College Allotted']) > 50 else row['Name of the College Allotted']
        print(f"{row['SL.NO']:>3} | {row['All India Rank']:>6} | {row['Course Code']:>7} | {college_short:<50} | {row['Course Name Allotted']:<12} | {row['Allotted Category']:<4} | ₹{row['Course_fees']:>9,}")

    print("="*140)

    # Save to Excel
    output_file = "24+Ayush+PSL+R1+KH.xlsx"

    with pd.ExcelWriter(output_file, engine='openpyxl') as writer:
        # Main data
        df.to_excel(writer, index=False, sheet_name='All Allotments')

        # College summary
        if df['Name of the College Allotted'].notna().sum() > 0:
            college_df = df[df['Name of the College Allotted'].str.strip() != '']
            if len(college_df) > 0:
                college_summary = college_df.groupby('Name of the College Allotted').agg({
                    'SL.NO': 'count',
                    'All India Rank': ['min', 'max'],
                    'Course_fees': 'first'
                }).reset_index()
                college_summary.columns = ['College', 'Total Seats', 'Best Rank', 'Last Rank', 'Fees']
                college_summary = college_summary.sort_values('Total Seats', ascending=False)
                college_summary.to_excel(writer, index=False, sheet_name='College Summary')

        # Category summary
        category_summary = df.groupby('Allotted Category').agg({
            'SL.NO': 'count',
            'All India Rank': ['min', 'max']
        }).reset_index()
        category_summary.columns = ['Category', 'Total Seats', 'Best Rank', 'Last Rank']
        category_summary.to_excel(writer, index=False, sheet_name='Category Summary')

    files.download(output_file)

    print(f"\n✅ SUCCESS! Saved as: {output_file}")
    print(f"📊 Total records: {len(df)}")
    print("="*140)